// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// check_completeness_list
LogicalVector check_completeness_list(List strg1_list, CharacterVector strg2, bool require_unique);
RcppExport SEXP _smutils_check_completeness_list(SEXP strg1_listSEXP, SEXP strg2SEXP, SEXP require_uniqueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type strg1_list(strg1_listSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strg2(strg2SEXP);
    Rcpp::traits::input_parameter< bool >::type require_unique(require_uniqueSEXP);
    rcpp_result_gen = Rcpp::wrap(check_completeness_list(strg1_list, strg2, require_unique));
    return rcpp_result_gen;
END_RCPP
}
// fast_round_time
Rcpp::NumericVector fast_round_time(Rcpp::NumericVector x, double precision, std::string method);
RcppExport SEXP _smutils_fast_round_time(SEXP xSEXP, SEXP precisionSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_round_time(x, precision, method));
    return rcpp_result_gen;
END_RCPP
}
// get_match_values
List get_match_values(List strg1_list, CharacterVector strg2, CharacterVector values);
RcppExport SEXP _smutils_get_match_values(SEXP strg1_listSEXP, SEXP strg2SEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type strg1_list(strg1_listSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type strg2(strg2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_match_values(strg1_list, strg2, values));
    return rcpp_result_gen;
END_RCPP
}
// get_match_values_list
List get_match_values_list(List strg1_list, List strg2, CharacterVector values);
RcppExport SEXP _smutils_get_match_values_list(SEXP strg1_listSEXP, SEXP strg2SEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type strg1_list(strg1_listSEXP);
    Rcpp::traits::input_parameter< List >::type strg2(strg2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_match_values_list(strg1_list, strg2, values));
    return rcpp_result_gen;
END_RCPP
}
// ma
Rcpp::NumericVector ma(NumericVector x, int k, String weighting);
RcppExport SEXP _smutils_ma(SEXP xSEXP, SEXP kSEXP, SEXP weightingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< String >::type weighting(weightingSEXP);
    rcpp_result_gen = Rcpp::wrap(ma(x, k, weighting));
    return rcpp_result_gen;
END_RCPP
}
// rle2
IntegerVector rle2(NumericVector x);
RcppExport SEXP _smutils_rle2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rle2(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_smutils_check_completeness_list", (DL_FUNC) &_smutils_check_completeness_list, 3},
    {"_smutils_fast_round_time", (DL_FUNC) &_smutils_fast_round_time, 3},
    {"_smutils_get_match_values", (DL_FUNC) &_smutils_get_match_values, 3},
    {"_smutils_get_match_values_list", (DL_FUNC) &_smutils_get_match_values_list, 3},
    {"_smutils_ma", (DL_FUNC) &_smutils_ma, 3},
    {"_smutils_rle2", (DL_FUNC) &_smutils_rle2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_smutils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
