# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check Completeness of String Lists Against Reference Vector
#'
#' Checks whether each character vector in a list contains only strings that
#' exist in a reference character vector, with optional uniqueness constraint.
#'
#' @param strg1_list List of character vectors to check
#' @param strg2 Character vector containing valid reference strings
#' @param require_unique Logical indicating whether strings in strg2 must be
#'   unique (appear exactly once). Default is TRUE.
#'
#' @return Logical vector of same length as strg1_list. Each element is:
#'   \itemize{
#'     \item TRUE if all strings in that list element exist in strg2 and meet
#'       uniqueness requirement
#'     \item FALSE if any string is not found or violates uniqueness constraint
#'     \item NA if the list element is NULL
#'   }
#'
#' @examples
#' \dontrun{
#' ref_strings <- c("a", "b", "c", "d")
#' test_list <- list(c("a", "b"), c("a", "e"), c("c"), NULL)
#' check_completeness_list(test_list, ref_strings)
#' }
#'
#' @export
check_completeness_list <- function(strg1_list, strg2, require_unique = TRUE) {
    .Call(`_smutils_check_completeness_list`, strg1_list, strg2, require_unique)
}

#' Round Time Values with Precision
#'
#' Rounds POSIXct or numeric time values to a specified precision using
#' various rounding methods. It does *not* work for rounding days because of timezone issues
#'
#' @param x Numeric or POSIXct vector of time values
#' @param precision Numeric value specifying rounding precision. Default is 1.0
#' @param method Character string specifying rounding method. Options are:
#'   \itemize{
#'     \item "round": Round to nearest (default)
#'     \item "floor": Round down
#'     \item "ceiling" or "ceil": Round up
#'   }
#'
#' @return Numeric vector of rounded values, preserving POSIXct class and
#'   timezone attributes if input was POSIXct
#'
#' @details
#' For time values, precision is typically in seconds. For example:
#' \itemize{
#'   \item precision = 1: Round to nearest second
#'   \item precision = 60: Round to nearest minute
#'   \item precision = 3600: Round to nearest hour
#' }
#'
#' @examples
#' \dontrun{
#' times <- as.POSIXct(c("2024-01-01 12:34:56", "2024-01-01 12:35:23"))
#' # Round to nearest minute
#' fast_round_time(times, precision = 60, method = "round")
#' }
#'
#' @export
fast_round_time <- function(x, precision = 1.0, method = "round") {
    .Call(`_smutils_fast_round_time`, x, precision, method)
}

#' Get Matching Values from Character Vectors
#'
#' For each character vector in a list, finds matching positions in a reference
#' character vector and returns corresponding values.
#'
#' @param strg1_list List of character vectors to search for
#' @param strg2 Character vector to search in (keys)
#' @param values Character vector of values corresponding to strg2
#'
#' @return List of same length as strg1_list. Each element contains:
#'   \itemize{
#'     \item Character vector of values from 'values' corresponding to matches in strg2
#'     \item NULL if the input list element was NULL
#'     \item Empty character vector if no matches found
#'   }
#'
#' @details
#' Creates a lookup map from strg2 to indices, then for each query string in
#' strg1_list elements, retrieves all corresponding values. If a string appears
#' multiple times in strg2, all corresponding values are returned.
#'
#' @examples
#' \dontrun{
#' keys <- c("a", "b", "c", "a")
#' vals <- c("1", "2", "3", "4")
#' queries <- list(c("a", "c"), c("b"), c("d"))
#' get_match_values(queries, keys, vals)
#' # Returns: list(c("1", "4", "3"), "2", character(0))
#' }
#'
#' @export
get_match_values <- function(strg1_list, strg2, values) {
    .Call(`_smutils_get_match_values`, strg1_list, strg2, values)
}

#' Get Matching Values from List of Character Vectors
#'
#' Similar to \code{get_match_values} but searches within a list of character
#' vectors instead of a single character vector.
#'
#' @param strg1_list List of character vectors to search for (queries)
#' @param strg2 List of character vectors to search in (keys)
#' @param values Character vector of values corresponding to list elements in strg2
#'
#' @return List of same length as strg1_list. Each element contains:
#'   \itemize{
#'     \item Character vector of values corresponding to matches
#'     \item NULL if the input list element was NULL
#'     \item Empty character vector if no matches found
#'   }
#'
#' @details
#' Creates a lookup map from all strings in strg2 list elements to their list
#' indices. For each query, retrieves values corresponding to the list positions
#' where matches were found.
#'
#' @examples
#' \dontrun{
#' key_list <- list(c("a", "b"), c("c", "d"), NULL, c("e"))
#' vals <- c("group1", "group2", "group3", "group4")
#' queries <- list(c("a", "c"), c("e"), c("f"))
#' get_match_values_list(queries, key_list, vals)
#' # Returns: list(c("group1", "group2"), "group4", character(0))
#' }
#'
#' @export
get_match_values_list <- function(strg1_list, strg2, values) {
    .Call(`_smutils_get_match_values_list`, strg1_list, strg2, values)
}

#' @title Moving-average imputation with simple, linear, or exponential weighting
#' @description
#' Imputes `NA` values in a numeric vector using a local moving-average
#' based on a window of size `2*k + 1` centered around each missing position.
#' Three weighting schemes are supported:
#' \itemize{
#'   \item \code{"simple"}: unweighted mean of non-missing neighbors,
#'   \item \code{"linear"}: weights \eqn{1 / (|i - j| + 1)},
#'   \item \code{"exponential"}: weights \eqn{1 / 2^{|i - j|}}.
#' }
#'
#' For each \code{NA} entry, the method expands the window symmetrically by
#' increasing \code{k} as needed until at least two non-missing values are found,
#' then computes the (weighted) average of the available neighbors to impute.
#' Non-NA elements are left unchanged.
#'
#' @param x Numeric vector with possible \code{NA}s to impute.
#' @param k Integer, the initial half-window size (the window is \code{2*k + 1}).
#' Must be \code{\link[base]{>=} 0}.
#' @param weighting Character string, one of \code{"simple"}, \code{"linear"},
#' or \code{"exponential"}.
#'
#' @details
#' The algorithm considers indices \code{i - k, ..., i + k} clipped to \code{[0, length(x)-1]}
#' for each missing \code{x[i]}. If fewer than two non-missing elements are present
#' in this window, \code{k} is increased by one and the process is retried,
#' until the requirement is satisfied. The final imputed value is the mean of
#' the available neighbors under the chosen weighting scheme. Elements of \code{x}
#' that are not \code{NA} are returned unchanged.
#'
#' Linear weights are normalized by their sum over the non-missing neighbors.
#' Exponential weights use base 2 and are similarly normalized. When the window
#' contains \code{NA}s, their corresponding weight contributions are set to zero.
#'
#' @return A numeric vector of the same length as \code{x} where missing values
#' have been imputed according to the chosen method.
#'
#' @examples
#' # Simple weighting
#' ma(c(1, NA, 3, NA, 5), k = 1, weighting = "simple")
#'
#' # Linear weighting
#' ma(c(10, NA, NA, 40, 50), k = 1, weighting = "linear")
#'
#' # Exponential weighting
#' set.seed(1)
#' x <- c(rnorm(5), NA, rnorm(5))
#' ma(x, k = 2, weighting = "exponential")
#'
#' # No change to non-missing values
#' ma(c(1, 2, 3), k = 1, weighting = "simple")
#'
#' @export
ma <- function(x, k, weighting) {
    .Call(`_smutils_ma`, x, k, weighting)
}

#' Run Length Encoding with Length per Element
#'
#' Computes run-length encoding but returns the length of each run for every
#' element in the input vector (instead of compressed run lengths).
#'
#' @param x Numeric vector to compute run lengths for
#'
#' @return Integer vector of same length as x, where each element contains
#'   the length of the run it belongs to
#'
#' @details
#' Unlike base R's \code{rle()}, this function returns a vector of the same
#' length as the input, with each position containing the length of its
#' corresponding run. Handles NA and NaN values correctly (consecutive NAs
#' are considered part of the same run).
#'
#' @examples
#' \dontrun{
#' x <- c(1, 1, 1, 2, 2, 3, 3, 3, 3)
#' rle2(x)
#' # Returns: c(3, 3, 3, 2, 2, 4, 4, 4, 4)
#' }
#'
#' @export
rle2 <- function(x) {
    .Call(`_smutils_rle2`, x)
}

